### ISSUE TITLE
RangeError: Maximum call stack size exceeded with jest

### ISSUE THREAD

**Issue by Innei** [skunight/nestjs-redis#50]
Hi, guys. I have some problem with jest test. If provider inject the redisService, then run test will crash `RangeError: Maximum call stack size exceeded`.

```ts
import { Module, Provider } from '@nestjs/common'
import { RedisModule } from 'nestjs-redis'
import { RedisNames } from './redis/redis.types'

@Module({
  imports: [
    RedisModule.register([
      {
        name: RedisNames.Access,
        keyPrefix: 'mx_access_',
      },
      {
        name: RedisNames.Like,
        keyPrefix: 'mx_like_',
      },
      {
        name: RedisNames.LoginRecord,
        keyPrefix: 'mx_' + RedisNames.LoginRecord + '_',
      },
    ]),
  ],
})
export class CommonModule {}
```

posts.service injected redis service.

```
FAIL  src/shared/posts/posts.service.spec.ts
  ● Test suite failed to run

    RangeError: Maximum call stack size exceeded

      at Object.genDebugFunction [as default] (node_modules/ioredis/built/utils/debug.js:52:26)
      at Object.genDebugFunction [as default] (node_modules/ioredis/built/utils/debug.js:53:31)
      at Object.genDebugFunction [as default] (node_modules/ioredis/built/utils/debug.js:53:31)
      at Object.genDebugFunction [as default] (node_modules/ioredis/built/utils/debug.js:53:31)
      at Object.genDebugFunction [as default] (node_modules/ioredis/built/utils/debug.js:53:31)
      at Object.genDebugFunction [as default] (node_modules/ioredis/built/utils/debug.js:53:31)
      at Object.genDebugFunction [as default] (node_modules/ioredis/built/utils/debug.js:53:31)
      at Object.genDebugFunction [as default] (node_modules/ioredis/built/utils/debug.js:53:31)
      at Object.genDebugFunction [as default] (node_modules/ioredis/built/utils/debug.js:53:31)
      at Object.genDebugFunction [as default] (node_modules/ioredis/built/utils/debug.js:53:31)
      at Object.genDebugFunction [as default] (node_modules/ioredis/built/utils/debug.js:53:31)
      at Object.genDebugFunction [as default] (node_modules/ioredis/built/utils/debug.js:53:31)
      at Object.genDebugFunction [as default] (node_modules/ioredis/built/utils/debug.js:53:31)
      at Object.genDebugFunction [as default] (node_modules/ioredis/built/utils/debug.js:53:31)
      at Object.genDebugFunction [as default] (node_modules/ioredis/built/utils/debug.js:53:31)
      at Object.genDebugFunction [as default] (node_modules/ioredis/built/utils/debug.js:53:31)
```

**Comment by skunight** [comment]
把src/shared/posts/posts.service.spec.ts贴出来看看

**Comment by Innei** [comment]
```ts
import { Test, TestingModule } from '@nestjs/testing'
import { PostsService } from './posts.service'

describe('PostsService', () => {
  let service: PostsService

  beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [PostsService],
    }).compile()

    service = module.get<PostsService>(PostsService)
  })

  it('should be defined', () => {
    expect(service).toBeDefined()
  })
})
```

**Comment by Innei** [comment]
是默认生成的，但是跑不通

**Comment by skunight** [comment]
Test.createTestingModule({
      providers: [PostsService],
 })
这里没有导入redis的module啊

**Comment by skunight** [comment]
你的单测要测什么？

**Comment by Innei** [comment]
还是 ` RangeError: Maximum call stack size exceeded` 难受了
```ts
 beforeEach(async () => {
    const module: TestingModule = await Test.createTestingModule({
      providers: [PostsService, RedisService],
      imports: [RedisModule.register([{
        name: RedisNames.Like,
        keyPrefix: 'mx_like_',
      },
      ])]
    }).compile()
```

**Comment by skunight** [comment]
你把完整的代码都贴出来，你单测的文件，以及你的service文件

**Comment by squareloop1** [comment]
I'm having exactly the same issue in unit tests. How was this issue resolved?
